//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab05
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_EMAIL
    {
        public int IdCustomer { get; set; }
        public int IdEmail { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMAIL EMAIL { get; set; }
    }
}
