//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab05
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMAIL()
        {
            this.CUSTOMER_EMAIL = new HashSet<CUSTOMER_EMAIL>();
        }
    
        public int IdEmail { get; set; }
        public string EmailTitle { get; set; }
        public string EmailContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_EMAIL> CUSTOMER_EMAIL { get; set; }
    }
}
